defaults:
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default


env_id: MountainCar-v0  # ID of the Gymnasium environment to use
seed: 2303  # Random seed for reproducibility

# Agent parameters
agent_type: PPO  # Proximal Policy Optimization algorithm
learning_rate: 0.0003  # Step size for optimizer updates
batch_size: 64  # Number of samples per optimization step
n_steps: 256  # Number of steps to run per update
gamma: 0.99  # Discount factor for future rewards (0-1)
clip_range: 0.2  # PPO clipping parameter for trust region

# Training parameters
total_timesteps: 10000  # Total number of timesteps to train
log_interval: 10  # Number of updates between logging events
